assets:
  bbq_sauce:
    scale: &id001
    - 2
    - 2
    - 2
    physics: RIGIDBODY
    usd: scene/example_assets/bbq_sauce/usd/bbq_sauce.usd
    urdf: scene/example_assets/bbq_sauce/urdf/bbq_sauce.urdf
    mjcf: scene/example_assets/bbq_sauce/mjcf/bbq_sauce.xml
scenario:
  sim: isaaclab
  num_envs: 1
  headless: false
  try_add_table: false
  task: task description placeholder
  cameras:
  - name: cam1
    width: 1024
    height: 1024
    pos:
    - 1.5
    - -1.5
    - 1.5
    look_at:
    - 0.0
    - 0.0
    - 0.0
  - name: cam2
    width: 1024
    height: 1024
    pos:
    - 0.3
    - 0.0
    - 2.5
    look_at:
    - 0.3
    - 0.0
    - 0.0
  objects:
  - name: bbq_sauce_1_1
    scale: *id001
    physics: RIGIDBODY
    usd: scene/example_assets/bbq_sauce/usd/bbq_sauce.usd
    urdf: scene/example_assets/bbq_sauce/urdf/bbq_sauce.urdf
    mjcf: scene/example_assets/bbq_sauce/mjcf/bbq_sauce.xml
  - name: bbq_sauce_1_2
    scale: *id001
    physics: RIGIDBODY
    usd: scene/example_assets/bbq_sauce/usd/bbq_sauce.usd
    urdf: scene/example_assets/bbq_sauce/urdf/bbq_sauce.urdf
    mjcf: scene/example_assets/bbq_sauce/mjcf/bbq_sauce.xml
  - name: bbq_sauce_1_3
    scale: *id001
    physics: RIGIDBODY
    usd: scene/example_assets/bbq_sauce/usd/bbq_sauce.usd
    urdf: scene/example_assets/bbq_sauce/urdf/bbq_sauce.urdf
    mjcf: scene/example_assets/bbq_sauce/mjcf/bbq_sauce.xml
  robots:
  - franka
initial_state:
  objects:
    bbq_sauce_1_1:
      pos:
      - 0.4000000059604645
      - -0.30000001192092896
      - 0.12999999523162842
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    bbq_sauce_1_2:
      pos:
      - 0.4000000059604645
      - 0.0
      - 0.12999999523162842
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    bbq_sauce_1_3:
      pos:
      - 0.4000000059604645
      - 0.30000001192092896
      - 0.12999999523162842
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
  robots:
    franka:
      pos:
      - 0.0
      - 0.0
      - 0.0
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      dof_pos:
        panda_joint1: 0.0
        panda_joint2: -0.785398
        panda_joint3: 0.0
        panda_joint4: -2.356194
        panda_joint5: 0.0
        panda_joint6: 1.570796
        panda_joint7: 0.785398
        panda_finger_joint1: 0.04
        panda_finger_joint2: 0.04
