assets:
  bbq_sauce: &id001
    scale:
    - 2
    - 2
    - 2
    physics: RIGIDBODY
    usd_path: scene/example_assets/bbq_sauce/usd/bbq_sauce.usd
    urdf_path: scene/example_assets/bbq_sauce/urdf/bbq_sauce.urdf
    mjcf_path: scene/example_assets/bbq_sauce/mjcf/bbq_sauce.xml
scenario:
  robots:
  - franka
  sim: isaaclab
  num_envs: 1
  headless: false
  try_add_table: false
  task: task description placeholder
  cameras:
  - name: cam1
    data_types:
    - rgb
    - depth
    width: 1024
    height: 1024
    pos:
    - 1.5
    - -1.5
    - 1.5
    look_at:
    - 0.0
    - 0.0
    - 0.0
    focal_length: 24.0
    focus_distance: 400.0
    horizontal_aperture: 20.955
    clipping_range:
    - 0.05
    - 100000.0
  - name: cam2
    data_types:
    - rgb
    - depth
    width: 1024
    height: 1024
    pos:
    - 0.3
    - 0.0
    - 2.5
    look_at:
    - 0.3
    - 0.0
    - 0.0
    focal_length: 24.0
    focus_distance: 400.0
    horizontal_aperture: 20.955
    clipping_range:
    - 0.05
    - 100000.0
  objects:
  - name: bbq_sauce_1
    <<: *id001
  - name: bbq_sauce_2
    <<: *id001
initial_state:
  objects:
    bbq_sauce_1:
      pos:
      - 0.4723726511001587
      - 0.33736568689346313
      - 0.12999999523162842
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    bbq_sauce_2:
      pos:
      - 0.8321294784545898
      - -0.2843162417411804
      - 0.12999999523162842
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
  robots:
    franka:
      pos:
      - 0.0
      - 0.0
      - 0.0
      rot:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      dof_pos:
        panda_joint1: 0.0
        panda_joint2: -0.785398
        panda_joint3: 0.0
        panda_joint4: -2.356194
        panda_joint5: 0.0
        panda_joint6: 1.570796
        panda_joint7: 0.785398
        panda_finger_joint1: 0.04
        panda_finger_joint2: 0.04
